package providers

const (
	// CONTRACT TYPES
	CONTRACT_TYPE_UNKNOWN uint64 = iota
	CONTRACT_TYPE_ERC20
	CONTRACT_TYPE_ERC721
	CONTRACT_TYPE_ERC777
	CONTRACT_TYPE_POAP
	CONTRACT_TYPE_GITCOIN
	// CONTRACT NAMES
	CONTRACT_NAME_UNKNOWN = "unknown"
	CONTRACT_NAME_ERC20   = "erc20"
	CONTRACT_NAME_ERC721  = "erc721"
	CONTRACT_NAME_ERC777  = "erc777"
	CONTRACT_NAME_POAP    = "poap"
	CONTRACT_NAME_GITCOIN = "gitcoinpassport"
)

var TokenTypeStringMap = map[uint64]string{
	CONTRACT_TYPE_UNKNOWN: CONTRACT_NAME_UNKNOWN,
	CONTRACT_TYPE_ERC20:   CONTRACT_NAME_ERC20,
	CONTRACT_TYPE_ERC721:  CONTRACT_NAME_ERC721,
	CONTRACT_TYPE_ERC777:  CONTRACT_NAME_ERC777,
	CONTRACT_TYPE_POAP:    CONTRACT_NAME_POAP,
	CONTRACT_TYPE_GITCOIN: CONTRACT_NAME_GITCOIN,
}

var TokenTypeIntMap = map[string]uint64{
	CONTRACT_NAME_UNKNOWN: CONTRACT_TYPE_UNKNOWN,
	CONTRACT_NAME_ERC20:   CONTRACT_TYPE_ERC20,
	CONTRACT_NAME_ERC721:  CONTRACT_TYPE_ERC721,
	CONTRACT_NAME_ERC777:  CONTRACT_TYPE_ERC777,
	CONTRACT_NAME_POAP:    CONTRACT_TYPE_POAP,
	CONTRACT_NAME_GITCOIN: CONTRACT_TYPE_GITCOIN,
}
