run:
        go: '1.22'
issues:
        max-same-issues: 0
        exclude-use-default: false
        exclude-files:
        - scanner/providers/gitcoin/gitcoin_stamps.go
linters:
        enable:
        - misspell
        - gofumpt
        - lll
        - staticcheck
        - unused
        - typecheck
        - ineffassign
        - errcheck
        - gosimple
        - goconst

linters-settings:
        lll:
                line-length: 130