version: "3.7"

services:
  census3:
    image: ghcr.io/vocdoni/census3:aragon
    build: .
    env_file: ".env"
    restart: always
    sysctls:
      net.core.somaxconn: 8128
    volumes:
      - census3:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.census3.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.census3.entrypoints=websecure"
      - "traefik.http.routers.census3.tls.certresolver=le"
      - "traefik.http.routers.census3.service=census3"
      - "traefik.http.services.census3.loadbalancer.server.port=${CENSUS3_PORT}"

  traefik:
    image: traefik:2.5
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=email@foo.bar"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    command: --interval 30 --cleanup


volumes:
  census3: {}
  traefik: {}

