// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"github.com/vocdoni/census3/db/annotations"
)

type FidAppkey struct {
	Fid    uint64
	AppKey annotations.Bytes
}

type LatestBlock struct {
	Contract    string
	BlockNumber int64
}

type User struct {
	Fid uint64
}
