// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"github.com/vocdoni/census3/db/annotations"
)

type LinkedevmFid struct {
	Fid        uint64
	EvmAddress []byte
}

type User struct {
	Fid             uint64
	Signer          annotations.Bytes
	CustodyAddress  annotations.Address
	AppKeys         annotations.Bytes
	RecoveryAddress annotations.Address
}
