// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: blocks.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/vocdoni/census3/db/types"
)

const blockByID = `-- name: BlockByID :one
SELECT id, timestamp, root_hash FROM Blocks
WHERE id = ?
LIMIT 1
`

func (q *Queries) BlockByID(ctx context.Context, id int64) (Block, error) {
	row := q.db.QueryRowContext(ctx, blockByID, id)
	var i Block
	err := row.Scan(&i.ID, &i.Timestamp, &i.RootHash)
	return i, err
}

const blockByRootHash = `-- name: BlockByRootHash :one
SELECT id, timestamp, root_hash FROM Blocks
WHERE root_hash = ?
LIMIT 1
`

func (q *Queries) BlockByRootHash(ctx context.Context, rootHash types.Hash) (Block, error) {
	row := q.db.QueryRowContext(ctx, blockByRootHash, rootHash)
	var i Block
	err := row.Scan(&i.ID, &i.Timestamp, &i.RootHash)
	return i, err
}

const blockByTimestamp = `-- name: BlockByTimestamp :one
SELECT id, timestamp, root_hash FROM Blocks
WHERE timestamp = ?
LIMIT 1
`

func (q *Queries) BlockByTimestamp(ctx context.Context, timestamp string) (Block, error) {
	row := q.db.QueryRowContext(ctx, blockByTimestamp, timestamp)
	var i Block
	err := row.Scan(&i.ID, &i.Timestamp, &i.RootHash)
	return i, err
}

const createBlock = `-- name: CreateBlock :execresult
INSERT INTO Blocks (
    id,
    timestamp,
    root_hash
)
VALUES (
    ?, ?, ?
)
`

type CreateBlockParams struct {
	ID        int64
	Timestamp string
	RootHash  types.Hash
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBlock, arg.ID, arg.Timestamp, arg.RootHash)
}

const deleteBlock = `-- name: DeleteBlock :execresult
DELETE FROM Blocks
WHERE id = ?
`

func (q *Queries) DeleteBlock(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBlock, id)
}

const paginatedBlocks = `-- name: PaginatedBlocks :many
SELECT id, timestamp, root_hash FROM Blocks
ORDER BY id
LIMIT ? OFFSET ?
`

type PaginatedBlocksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginatedBlocks(ctx context.Context, arg PaginatedBlocksParams) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, paginatedBlocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(&i.ID, &i.Timestamp, &i.RootHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlock = `-- name: UpdateBlock :execresult
UPDATE Blocks
SET timestamp = ?,
    root_hash = ?
WHERE id = ?
`

type UpdateBlockParams struct {
	Timestamp string
	RootHash  types.Hash
	ID        int64
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBlock, arg.Timestamp, arg.RootHash, arg.ID)
}
