// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"database/sql"

	"github.com/vocdoni/census3/db/annotations"
)

type Block struct {
	ID        int64
	Timestamp string
	RootHash  annotations.Hash
}

type CensusBlock struct {
	CensusID int
	BlockID  int64
}

type Censuse struct {
	ID         int
	StrategyID int
	MerkleRoot annotations.Hash
	Uri        sql.NullString
	Size       int
	Weight     sql.NullString
	CensusType int
	QueueID    string
}

type Holder struct {
	ID annotations.Address
}

type Strategy struct {
	ID        int
	Predicate string
}

type StrategyToken struct {
	StrategyID int
	TokenID    []byte
	MinBalance []byte
	MethodHash []byte
}

type Token struct {
	ID            annotations.Address
	Name          sql.NullString
	Symbol        sql.NullString
	Decimals      int
	TotalSupply   annotations.BigInt
	CreationBlock sql.NullInt64
	TypeID        int
	Synced        bool
	Tag           sql.NullString
	ChainID       int64
}

type TokenHolder struct {
	TokenID  []byte
	HolderID []byte
	Balance  []byte
	BlockID  int64
}

type TokenType struct {
	ID       int
	TypeName string
}
