// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package queries

import (
	"database/sql"

	"go.vocdoni.io/census3/db/types"
)

type Block struct {
	ID        int64
	Timestamp string
	RootHash  types.Hash
}

type Censusblock struct {
	CensusID int64
	BlockID  int64
}

type Censuses struct {
	ID         int64
	StrategyID int64
	MerkleRoot types.Hash
	Uri        sql.NullString
}

type Holder struct {
	ID types.Address
}

type Strategy struct {
	ID        int64
	Predicate string
}

type Strategytoken struct {
	StrategyID int64
	TokenID    types.Address
	MinBalance types.BigInt
	MethodHash types.MethodHash
}

type Token struct {
	ID            types.BigInt
	Name          sql.NullString
	Symbol        sql.NullString
	Decimals      sql.NullInt32
	TotalSupply   types.Address
	CreationBlock int64
	TypeID        int64
}

type Tokenholder struct {
	TokenID  types.Address
	HolderID types.Address
	Balance  types.BigInt
	BlockID  int64
}

type Tokentype struct {
	ID       int64
	TypeName string
}
