// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: tokenTypes.sql

package queries

import (
	"context"
	"database/sql"
)

const createTokenType = `-- name: CreateTokenType :execresult
INSERT INTO token_types (type_name)
VALUES (?)
`

func (q *Queries) CreateTokenType(ctx context.Context, typeName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTokenType, typeName)
}

const deleteTokenType = `-- name: DeleteTokenType :execresult
DELETE FROM token_types
WHERE id = ?
`

func (q *Queries) DeleteTokenType(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTokenType, id)
}

const listTokenTypes = `-- name: ListTokenTypes :many
SELECT id, type_name FROM token_types
ORDER BY id
`

func (q *Queries) ListTokenTypes(ctx context.Context) ([]TokenType, error) {
	rows, err := q.db.QueryContext(ctx, listTokenTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenType
	for rows.Next() {
		var i TokenType
		if err := rows.Scan(&i.ID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenTypeByID = `-- name: TokenTypeByID :one
SELECT id, type_name FROM token_types
WHERE id = ?
LIMIT 1
`

func (q *Queries) TokenTypeByID(ctx context.Context, id uint64) (TokenType, error) {
	row := q.db.QueryRowContext(ctx, tokenTypeByID, id)
	var i TokenType
	err := row.Scan(&i.ID, &i.TypeName)
	return i, err
}

const tokenTypeByName = `-- name: TokenTypeByName :one
SELECT id, type_name FROM token_types
WHERE type_name = ?
LIMIT 1
`

func (q *Queries) TokenTypeByName(ctx context.Context, typeName string) (TokenType, error) {
	row := q.db.QueryRowContext(ctx, tokenTypeByName, typeName)
	var i TokenType
	err := row.Scan(&i.ID, &i.TypeName)
	return i, err
}

const updateTokenType = `-- name: UpdateTokenType :execresult
UPDATE token_types
SET type_name = ?
WHERE id = ?
`

type UpdateTokenTypeParams struct {
	TypeName string
	ID       uint64
}

func (q *Queries) UpdateTokenType(ctx context.Context, arg UpdateTokenTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTokenType, arg.TypeName, arg.ID)
}
