package web3

const (
	// OTHER CONSTANTS
	MAX_SCAN_BLOCKS_PER_ITERATION           = 1000000
	MAX_SCAN_LOGS_PER_ITERATION             = 80000
	MAX_NEW_HOLDER_CANDIDATES_PER_ITERATION = 5000
	BLOCKS_TO_SCAN_AT_ONCE                  = uint64(5000)
	NULL_ADDRESS                            = "0"
)
